[tools]
node = "lts"
"npm:difit" = "latest"
"npm:dotenv-cli" = "latest"
"npm:opencode-ai" = "latest"
pnpm = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
package_manager = "pnpm"
